### ISSUE TITLE
[BUG] Crash on update from 4.16 to 4.18

### ISSUE THREAD

**Issue by LivingWithHippos** [LivingWithHippos/unchained-android#158]
QUICK SOLUTION: uninstall the app, reinstall and clear the data (just to be sure) and then start it

**Describe the bug**
The app start and crashes after the first loading screen

**To Reproduce**
1. Log in on the production 4.16 version of the app with the private api token
2. Updated to 4.18
3. open the app

**Additional context**
Need to check:
- Only happen with the production version of the app
- Only happen with the private api key

Error:

```java
FATAL EXCEPTION: main
Process: com.github.livingwithhippos.unchained, PID: 8405
java.lang.IllegalArgumentException: Navigation action/destination com.github.livingwithhippos.unchained:id/action_startFragment_to_userProfileFragment cannot be found from the current destination a(com.github.livingwithhippos.unchained:id/user_dest) label=Utente class=com.github.livingwithhippos.unchained.user.view.UserProfileFragment
 at androidx.navigation.NavController.g(:10)
 at s2.b.a(:25)
 at androidx.lifecycle.LiveData.b(Unknown Source:29)
 at androidx.lifecycle.LiveData.c(Unknown Source:44)
 at d1.z.k(:1)
 at androidx.lifecycle.LiveData$a.run(Unknown Source:18)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:246)
 at android.app.ActivityThread.main(ActivityThread.java:8512)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

It's a navigation error, I think when the credentials are retrieved the navigation to the user fragment is launched and then another credential is found and the navigation gets called again but the starting point has changed to the user fragment so it crashes. The code crashing is this:

```kotlin

is AuthenticationStatus.Authenticated -> {
                        val action = StartFragmentDirections.actionStartFragmentToUserProfileFragment()
                        findNavController().navigate(action)
                    }
                    is AuthenticationStatus.AuthenticatedNoPremium -> {
                            val action =
                                StartFragmentDirections.actionStartFragmentToUserProfileFragment()
                            findNavController().navigate(action)
                    }
```

This is (probably) the code called multiple times

```kotlin

    private suspend fun getUser(updateAuthStatus: Boolean = true) = flow {
        protoStore.credentialsFlow.collect { credentials ->
   ...
   newAuthenticationState.postEvent(
                                    AuthenticationStatus.Authenticated(
                                        userResult.success
                                    )
                                )
   }
```

also protoStore.deleteCredentials() does not seem to work

**Comment by LivingWithHippos** [comment]
Temporarily fixed by adding a try catch to the navigation. Update to 4.18.4

**Comment by LivingWithHippos** [comment]
The problem was that the credentials were recovered once in the activity and once in the fragment, triggering the navigation twice. removed retrieval from the fragment
