### ISSUE TITLE
Fatal application crash

### ISSUE THREAD

**Issue by andronedev** [LivingWithHippos/unchained-android#332]
**Describe the bug**
the application crashes completely when clicking to see more information on a torrent

**To Reproduce**
1. Go to torrents tabs
2. Click on a torrent
3. App crash completely

**Screenshots**
*nothing to see because the application closes completely lol*

**Smartphone (please complete the following information):**
 - Device: Xiaomi redmi note 10s
 - OS: Android 13 - Miui 14 (rooted with magisk and lsposed installed, but lsposed has no impact because it didn't work without lsposed either)

**Additional context**
- App Version: 1.1.1

**Logs :**
```
FATAL EXCEPTION: main
Process: com.github.livingwithhippos.unchained, PID: 19866
android.content.res.Resources$NotFoundException: Plural resource ID #0x7f120004 quantity=3 item=other
	at android.content.res.ResourcesImpl.getQuantityText(ResourcesImpl.java:348)
	at android.content.res.Resources.getQuantityText(Resources.java:547)
	at android.content.res.Resources.getQuantityString(Resources.java:623)
	at v3.d0.p0(SourceFile:334)
	at androidx.databinding.e.q0(SourceFile:19)
	at androidx.activity.j.b(SourceFile:56)
	at androidx.activity.j.run(SourceFile:511)
	at androidx.databinding.d.doFrame(SourceFile:501)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1384)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1013)
	at android.view.Choreographer.doFrame(Choreographer.java:904)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1366)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8232)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

```

**Comment by LivingWithHippos** [comment]
Can you test this apk? (you'll need to unzip it first)

[com.github.livingwithhippos.unchained.debug-v1.zip](https://github.com/LivingWithHippos/unchained-android/files/13646849/com.github.livingwithhippos.unchained.debug-v1.zip)

**Comment by andronedev** [comment]
Sorry I didn't reply before, it seems to work fine 👍 thanks!
